source 'https://github.com/CocoaPods/Specs.git'

#use_frameworks!
use_modular_headers!

def common
    pod 'YTXDTNWBWeexContainerBusinessModule', :path => '../'
end

target 'YTXDTNWBWeexContainerBusinessModuleAppExample' do
  common
  pod 'FMDB'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            if target.name != "YTXDTNWBWeexContainerBusinessModule" || target.name != "YTXDTNWBWeexContainerBusinessModuleAppExample" then
                config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
            end
        end
    end
end
